services:
  bot:
    build: .
    restart: no
    hostname: bot
    depends_on:
      maria-db:
        condition: service_healthy
  maria-db:
    image: "mariadb:latest"
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: leckerschmecker
      MYSQL_DATABASE: leckerschmecker
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
